networks:
  spaccel_network:
    name: ${SPACCEL_NETWORK}
    external: true

services:
  nginx:
    image: nginx:1.22
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - php-fpm
    networks:
      - spaccel_network

  php-fpm:
    build: ./.docker/php/fpm
    env_file:
      - ./.env
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - ./.docker/php/fpm/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/php/fpm/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./app:/app
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app
    networks:
      - spaccel_network

  mysql:
    image: mysql:8.0.30
    env_file:
      - ./.env
    ports:
      - '3307:3306'
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./.docker/.mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin' ,'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - spaccel_network
